# mod properties
modid=skyguis
group=de.melanx
base_version=2.1

# dependencies
forge_version=1.19.1-42.0.1
#mappings=sugarcane_2022.05.22-1.18.2

# upload properties
upload_release=beta
upload_versions=1.19.1, 1.19.2
upload_requirements=libx, skyblock-builder
modrinth_project=3Gdi7Qgq
curse_project=557696

# misc
remote_maven=https://maven.melanx.de/release
license=The Apache License, Version 2.0
license_url=https://www.apache.org/licenses/LICENSE-2.0.txt
