modLoader="javafml"
loaderVersion="[40,)"
license="The Apache License, Version 2.0"
issueTrackerURL="https://github.com/MelanX/SkyGUIs/issues"

[[mods]]
modId="skyguis"
version="${file.jarVersion}"
displayName="Sky GUIs"
updateJSONURL="https://assets.melanx.de/updates/sky-guis.json"
displayURL="www.curseforge.com/members/melanx/"
authors="MelanX"
description="""
An addon for Skyblock Builder which provides GUIs to easily modify and view teams.
"""

[[dependencies.skyguis]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.19,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.skyguis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2, 1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.skyguis]]
    modId="skyblockbuilder"
    mandatory=true
    versionRange="[1.18.2-3.3.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.skyguis]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.2-3.2.2,)"
    ordering="AFTER"
    side="BOTH"
