modLoader="javafml"
loaderVersion="[41,)"
license="The Apache License, Version 2.0"
issueTrackerURL="https://github.com/MelanX/SkyGUIs/issues"

[[mods]]
modId="skyguis"
version="${file.jarVersion}"
displayName="Sky GUIs"
updateJSONURL="https://assets.melanx.de/updates/sky-guis.json"
displayURL="www.curseforge.com/members/melanx/"
authors="MelanX"
description="""
An addon for Skyblock Builder which provides GUIs to easily modify and view teams.
"""

[[dependencies.skyguis]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.98,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.skyguis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19, 1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.skyguis]]
    modId="skyblockbuilder"
    mandatory=true
    versionRange="[1.19-4.0.12,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.skyguis]]
    modId="libx"
    mandatory=true
    versionRange="[1.19-4.0.7,)"
    ordering="AFTER"
    side="BOTH"
